LaserAfzar.Web/Controllers/CompanyServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LaserAfzar.Entities;
using LaserAfzar.Web.DataContext;
using LaserAfzar.Web.Models;

namespace LaserAfzar.Web.Controllers
{
    [Authorize]
    public class CompanyServicesController : Controller
    {
        private CompanyServiceDbContext db = new CompanyServiceDbContext();

        // GET: CompanyServices
        public async Task<ActionResult> Index()
        {
            var companyServices = db.CompanyServices.Include(c => c.ServiceTitleImage);
            return View(await companyServices.ToListAsync());
        }

        // GET: CompanyServices/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyService companyService = await db.CompanyServices.FindAsync(id);
            if (companyService == null)
            {
                return HttpNotFound();
            }
            return View(companyService);
        }

        // GET: CompanyServices/Create
        public ActionResult Create()
        {
            ViewBag.CompanyServiceId = new SelectList(db.ServiceTitleImages, "ServiceTitleImageId", "Title");
            return View();
        }

        // POST: CompanyServices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CompanyServiceId,Title,BriefDescription,FullDescription")] CompanyService companyService)
        {
            if (ModelState.IsValid)
            {
                db.CompanyServices.Add(companyService);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyServiceId = new SelectList(db.ServiceTitleImages, "ServiceTitleImageId", "Title", companyService.CompanyServiceId);
            return View(companyService);
        }

        // GET: CompanyServices/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyService companyService = await db.CompanyServices.FindAsync(id);
            if (companyService == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyServiceId = new SelectList(db.ServiceTitleImages, "ServiceTitleImageId", "Title", companyService.CompanyServiceId);
            return View(companyService);
        }

        // POST: CompanyServices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CompanyServiceId,Title,BriefDescription,FullDescription")] CompanyService companyService)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyService).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyServiceId = new SelectList(db.ServiceTitleImages, "ServiceTitleImageId", "Title", companyService.CompanyServiceId);
            return View(companyService);
        }

        // GET: CompanyServices/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyService companyService = await db.CompanyServices.FindAsync(id);
            if (companyService == null)
            {
                return HttpNotFound();
            }
            return View(companyService);
        }

        // POST: CompanyServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CompanyService companyService = await db.CompanyServices.FindAsync(id);
            //delete service image title
            if (companyService.ServiceTitleImage != null)
            {
                PhotoFileManager manager = new PhotoFileManager(PhotoManagerType.ServiceTitle);
                manager.Delete(companyService.ServiceTitleImage.FileName, false);

                db.ServiceTitleImages.Remove(companyService.ServiceTitleImage);
            }

            //delete all subservices + subservices images
            if (companyService.SubServices != null)
            {
                List<SubService> subServicesList = companyService.SubServices.ToList();
                PhotoFileManager manager = new PhotoFileManager(PhotoManagerType.Service);
                foreach (var item in subServicesList)
                {
                    //remove all subservice images
                    List<ServiceImage> serviceImagesList = item.ServiceImage.ToList();
                    foreach (var imageItem in serviceImagesList)
                    {
                        //remove subservice image file
                        manager.Delete(imageItem.FileName, true);

                        //remove subservice image from db
                        db.ServiceImages.Remove(imageItem);
                    }

                    //remove subservice
                    db.SubServices.Remove(item);
                }
            }
            

            db.CompanyServices.Remove(companyService);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaserAfzar.Web/Controllers/ServiceImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LaserAfzar.Entities;
using LaserAfzar.Web.DataContext;
using LaserAfzar.Web.Models;

namespace LaserAfzar.Web.Controllers
{
    [Authorize]
    public class ServiceImagesController : Controller
    {
        private CompanyServiceDbContext db = new CompanyServiceDbContext();

        // GET: ServiceImages
        public async Task<ActionResult> Index(int id, int CompanyServiceId)
        {
            ViewBag.SubServiceId = id;
            ViewBag.CompanyServiceId = CompanyServiceId;
            return View(await db.ServiceImages.Where( s => s.SubService.SubServiceId == id).ToListAsync());
        }

        // GET: ServiceImages/Details/5
        public async Task<ActionResult> Details(int? id, int SubServiceId, int CompanyServiceId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceImage serviceImage = await db.ServiceImages.FindAsync(id);
            if (serviceImage == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubServiceId = SubServiceId;
            ViewBag.CompanyServiceId = CompanyServiceId;
            ViewBag.ImageType = PhotoManagerType.Service;
            ViewBag.ImageDirectory = PhotoFileManager.StorageDirectoryDetection(PhotoManagerType.Service);
            return View(serviceImage);
        }

        // GET: ServiceImages/Create
        public ActionResult Create(int id, int CompanyServiceId)
        {
            ViewBag.SubServiceId = id;
            ViewBag.CompanyServiceId = CompanyServiceId;
            ViewBag.ImageType = PhotoManagerType.Service;
            ViewBag.ImageDirectory = PhotoFileManager.StorageDirectoryDetection(PhotoManagerType.Service);

            return View();
        }

        // POST: ServiceImages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ServiceImageId,Title,FileName")] ServiceImage serviceImage, int SubServiceId, int CompanyServiceId)
        {
            if (ModelState.IsValid)
            {
                serviceImage.SubService = db.SubServices.Find(SubServiceId);
                db.ServiceImages.Add(serviceImage);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { id = SubServiceId, CompanyServiceId = CompanyServiceId });
            }

            return View(serviceImage);
        }

        // GET: ServiceImages/Edit/5
        public async Task<ActionResult> Edit(int? id, int SubServiceId, int CompanyServiceId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceImage serviceImage = await db.ServiceImages.FindAsync(id);
            if (serviceImage == null)
            {
                return HttpNotFound();
            }

            ViewBag.SubServiceId = SubServiceId;
            ViewBag.CompanyServiceId = CompanyServiceId;
            ViewBag.ImageType = PhotoManagerType.Service;
            ViewBag.ImageDirectory = PhotoFileManager.StorageDirectoryDetection(PhotoManagerType.Service);
            return View(serviceImage);
        }

        // POST: ServiceImages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ServiceImageId,Title,FileName")] ServiceImage serviceImage, int SubServiceId, int CompanyServiceId)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceImage).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { id = SubServiceId, CompanyServiceId = CompanyServiceId } );
            }
            return View(serviceImage);
        }

        // GET: ServiceImages/Delete/5
        public async Task<ActionResult> Delete(int? id, int SubServiceId, int CompanyServiceId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceImage serviceImage = await db.ServiceImages.FindAsync(id);
            if (serviceImage == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubServiceId = SubServiceId;
            ViewBag.CompanyServiceId = CompanyServiceId;
            ViewBag.ImageType = PhotoManagerType.Service;
            ViewBag.ImageDirectory = PhotoFileManager.StorageDirectoryDetection(PhotoManagerType.Service);
            return View(serviceImage);
        }

        // POST: ServiceImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, string deleteFileName, int SubServiceId, int CompanyServiceId)
        {
            //delete image file first
            PhotoFileManager manager = new PhotoFileManager(PhotoManagerType.Service);
            manager.Delete(deleteFileName, true);

            ServiceImage serviceImage = await db.ServiceImages.FindAsync(id);
            db.ServiceImages.Remove(serviceImage);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new { id = SubServiceId, CompanyServiceId = CompanyServiceId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaserAfzar.Web/Views/SubServices/Create.cshtml
@model LaserAfzar.Entities.SubService

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SubService</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <input type="hidden" name="CompanyServiceId" id="CompanyServiceId" value="@ViewBag.CompanyServiceId" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.CompanyServiceId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $("#Description").htmlarea();
    </script>
}

LaserAfzar.Web/Views/SubServices/Delete.cshtml
@model LaserAfzar.Entities.SubService

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubService</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = ViewBag.CompanyServiceId })
        </div>


        <input type="hidden" name="companyservicesID" id="companyservicesID" value=@ViewBag.companyServiceId />
    }
</div>

LaserAfzar.Web/Views/SubServices/Details.cshtml
@model LaserAfzar.Entities.SubService

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SubService</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubServiceId, CompanyServiceId = ViewBag.CompanyServiceId }) |
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.CompanyServiceId })
</p>

LaserAfzar.Web/Views/SubServices/Edit.cshtml
@model LaserAfzar.Entities.SubService

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SubService</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SubServiceId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <input type="hidden" name="companyservicesID" id="companyservicesID" value=@ViewBag.companyServiceId />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.CompanyServiceId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $("#Description").htmlarea();
    </script>
}

LaserAfzar.Web/Views/SubServices/Index.cshtml
@model IEnumerable<LaserAfzar.Entities.SubService>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Sub Services Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.CompanyServiceId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Images
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @if (item.Description.Length >= 20)
                {
                    @Html.DisplayFor(modelItem => item.Description).ToString().Substring(0,20)@:...
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Description)
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Index", "ServiceImages", new { id = item.SubServiceId, CompanyServiceId = ViewBag.CompanyServiceId }, null)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.SubServiceId, CompanyServiceId = ViewBag.CompanyServiceId }) |
                @Html.ActionLink("Details", "Details", new { id = item.SubServiceId, CompanyServiceId = ViewBag.CompanyServiceId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.SubServiceId, CompanyServiceId = ViewBag.CompanyServiceId })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to Services", "Index", "CompanyServices")
</div>