LaserAfzar.Web/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaserAfzar.Web.Controllers
{
    [Authorize]
    public class AdminPanelController : Controller
    {
        // GET: AdminPanel
        public ActionResult Index()
        {
            return View();
        }
    }
}

LaserAfzar.Web/Controllers/CompanyMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LaserAfzar.Entities;
using LaserAfzar.Web.DataContext;
using LaserAfzar.Web.Models;

namespace LaserAfzar.Web.Controllers
{
    [Authorize]
    public class CompanyMembersController : Controller
    {
        private CompanyMemberDbContext db = new CompanyMemberDbContext();

        // GET: CompanyMembers
        public async Task<ActionResult> Index()
        {
            var companyMembers = db.CompanyMembers.Include(c => c.CompanyMemberImage);
            return View(await companyMembers.ToListAsync());
        }

        // GET: CompanyMembers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMember companyMember = await db.CompanyMembers.FindAsync(id);
            if (companyMember == null)
            {
                return HttpNotFound();
            }
            return View(companyMember);
        }

        // GET: CompanyMembers/Create
        public ActionResult Create()
        {
            ViewBag.CompanyMemberID = new SelectList(db.CompanyMemberImages, "CompanyMemberImageId", "Title");
            return View();
        }

        // POST: CompanyMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CompanyMemberID,Name,JobTitle,Message")] CompanyMember companyMember)
        {
            if (ModelState.IsValid)
            {
                db.CompanyMembers.Add(companyMember);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyMemberID = new SelectList(db.CompanyMemberImages, "CompanyMemberImageId", "Title", companyMember.CompanyMemberID);
            return View(companyMember);
        }

        // GET: CompanyMembers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMember companyMember = await db.CompanyMembers.FindAsync(id);
            if (companyMember == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyMemberID = new SelectList(db.CompanyMemberImages, "CompanyMemberImageId", "Title", companyMember.CompanyMemberID);
            return View(companyMember);
        }

        // POST: CompanyMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CompanyMemberID,Name,JobTitle,Message")] CompanyMember companyMember)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyMember).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyMemberID = new SelectList(db.CompanyMemberImages, "CompanyMemberImageId", "Title", companyMember.CompanyMemberID);
            return View(companyMember);
        }

        // GET: CompanyMembers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyMember companyMember = await db.CompanyMembers.FindAsync(id);
            if (companyMember == null)
            {
                return HttpNotFound();
            }
            return View(companyMember);
        }

        // POST: CompanyMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CompanyMember companyMember = await db.CompanyMembers.FindAsync(id);

            //delete member image id existed
            if(companyMember.CompanyMemberImage != null)
            {
                //delete image file first 
                PhotoFileManager manager = new PhotoFileManager(PhotoManagerType.Member);
                manager.Delete(companyMember.CompanyMemberImage.FileName, false);

                //delete image from db
                db.CompanyMemberImages.Remove(companyMember.CompanyMemberImage);
            }

            db.CompanyMembers.Remove(companyMember);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LaserAfzar.Web/Controllers/ProjectImagesController.cs
using LaserAfzar.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaserAfzar.Web.Controllers
{
    [Authorize]
    public class ProjectImagesController : Controller
    {
        // GET: ProjectImages
        public ActionResult Create()
        {
            return View();
        }



        //upload async action
        public ActionResult AsyncUpload()
        {
            return View();
        }

        //upload async action post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AsyncUpload(IEnumerable<HttpPostedFileBase> files, PhotoManagerType imageType)
        {
            PhotoFileManager manager = new PhotoFileManager(files, imageType);

            if(imageType == PhotoManagerType.Service)
                return manager.Upload(true, 300);

            return manager.Upload(false, null);
        }

        public ActionResult AsyncDelete()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AsyncDelete(string deleteFileName, PhotoManagerType DeleteImageType)
        {
            PhotoFileManager manager = new PhotoFileManager(DeleteImageType);

            if (DeleteImageType == PhotoManagerType.Service)
                return manager.Delete(deleteFileName, true);

            return manager.Delete(deleteFileName, false);
        }

    }
}

LaserAfzar.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/cssAdmin")
    @Styles.Render("~/Content/jHtmlArea/jHtmlAreacss")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LaserAfzar", "Index", "AdminPanel", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("AboutUs", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Features", "Index", "Features")</li>
                    <li>@Html.ActionLink("Members", "Index", "CompanyMembers")</li>
                    <li>@Html.ActionLink("ContactUs", "Index", "ContactUs")</li>
                    <li>@Html.ActionLink("Services", "Index", "CompanyServices")</li>
                    <li>@Html.ActionLink("WebSite", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jHtmlAreajs")
    @RenderSection("scripts", required: false)
</body>
</html>

LaserAfzar.Web/Views/Shared/_ContactUsPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-3 contactinfo-icon">
            <a><i class="fas fa-map-marker fa-7x"></i></a>
        </div>
        <div class="col-xs-12 col-sm-9 contactinfo-desc">
            <a class="address"><address>ایران  تهران  میدان هروی  خیابان شهید پناهی نیا  کوچه سوم  پلاک ۴۸</address></a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-3 contactinfo-icon">
            <a href="tel:+989121204845"><i class="fas fa-phone-square fa-6x"></i></a>
        </div>
        <div class="col-xs-12 col-sm-9 contactinfo-desc">
            <a href="tel:+989121204845" class="tel-number">+۹۸۹۱۲۱۲۰۴۸۴۵</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-3 contactinfo-icon">
            <a><i id="contactus-toggle-button" class="far fa-envelope fa-6x"></i></a>
        </div>
        <div class="col-xs-12 col-sm-9 contactinfo-desc">
            <a href="mailto:support@LaserAfzar.ir" class="email-address">support@LaserAfzar.ir</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-3 contactinfo-icon">
            <a href="/ContactUs/UserContactUS"><i id="contactus-toggle-button" class="fas fa-file-alt fa-7x"></i></a>
        </div>
        <div class="col-xs-12 col-sm-9 contactinfo-desc">
            <a href="/ContactUs/UserContactUS">فرم تماس با ما</a>
        </div>
    </div>
</div>

LaserAfzar.Web/Views/Shared/_DeleteImagePreview.cshtml
<div class="row">

    <div class="is-table-row" id="uploadResultBox">
        <div class="col-xs-10 upload-preview-div align-middle justify-content-center text-center">
            <img id="imgUploadedResult" class="img-result" src="../../../@ViewBag.ImageDirectory/@Model.FileName">
        </div>
    </div>
</div>

LaserAfzar.Web/Views/Shared/_ImageUpload.cshtml
@{ 
    var FileName = "";
    if(Model != null)
    {
        FileName = Model.FileName;
    }
}



@using (Ajax.BeginForm("AsyncDelete", "ProjectImages", null , new AjaxOptions() { HttpMethod = "POST" }, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()




    <div class="is-table-row" id="uploadResultBox">
        <div class="col-xs-10 upload-preview-div align-middle justify-content-center text-center">
            <img id="imgUploadedResult" class="img-result" src="../../@ViewBag.ImageDirectory/@FileName">
        </div>
        <div id="uploadResultBoxDeleteSection" class="col-xs-2 delete-Button-div align-middle justify-content-center text-center">
            <input type="submit" value="Delete File" class="btn btn-danger">

            <input type="hidden" value="@FileName" id="deleteFileName" name="deleteFileName" />
            <input type="hidden" name="DeleteImageType" id="DeleteImageType" value="@ViewBag.ImageType" />
        </div>
    </div>

}

@using (Ajax.BeginForm("AsyncUpload", "ProjectImages", null, new AjaxOptions() { HttpMethod = "POST" }, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row" id="uploadFormBox">
        <div class="col-xs-12">
            <label for="fileUploadInput" class="custom-file-upload">
                Upload File
            </label>
            <input id="fileUploadInput" type="file" name="files" />
            <input type="hidden" name="ImageType" id="ImageType" value="@ViewBag.ImageType" />
        </div>
    </div>


    <div class="form-group" id="uploadProgressBox">
        <div class="progress col-md-2" id="uploadProgressBar">
            <div class="progress-bar">0%</div>
        </div>
    </div>


}

LaserAfzar.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewBag.Title - LaserAfzar.ir Application</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    @Styles.Render("~/Content/preCss")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header id="top">
        <nav class="navbar navbar-inverse navbar-fixed-top cbp-af-header"
             role="navigation"
             aria-label="site">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/">
                        <img src="/Images/site/LaserAfzar_logo.png" alt="LaserAfzar Logo" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="navbar-link-href" href="#top">خانه</a></li>
                        <li><a class="navbar-link-href" href="#aboutus">درباره ما</a></li>
                        <li><a class="navbar-link-href" href="#services">خدمات</a></li>
                        <li><a class="navbar-link-href" href="#contactus">ارتباط با ما</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - LaserAfzar.ir</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/navAnim")
    @Scripts.Render("~/bundles/easing")
    @Scripts.Render("~/bundles/WowJs")
    @Scripts.Render("~/bundles/StellarJs")
    @Scripts.Render("~/bundles/nanoGallery")
    @Scripts.Render("~/bundles/AngularJs")
    @Scripts.Render("~/bundles/scrolling")
    @RenderSection("scripts", required: false)
</body>
</html>